services:
  flaskapi:
    build: ./flaskapi
    ports:
      - 5001:5000
    volumes:
      - ./storage:/app/storage
    depends_on:
      - mongodb
    env_file:
      - ./flaskapi/.env
    
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
